name: Fetch data

on:
  workflow_dispatch

jobs:
  build_pages:
    name: Copy data to repo
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx6g
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4
    - name: Install Saxon, Ant
      run: |
        apt-get update && apt-get install openjdk-11-jre-headless ant -y --no-install-recommend
        ./dl_saxon.sh
    - name: Fetch and preprocess Data
      run: |
        ./fetch_data.sh
    - name: Generate CSV from list XML files
      run: |
        python3 process_list_xml.py
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Downloaded/Updated Data
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
