name: Build and publish

on:
  workflow_dispatch

jobs:
  build_pages:
    name: Copy data to repo
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx6g
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v2
    - name: Install Saxon, Ant and Fundament
      run: |
        apt-get update && apt-get install openjdk-11-jre-headless ant -y --no-install-recommend
        ./script.sh
    - name: Install Ant-Contrib and Python
      run: |
        wget https://repo1.maven.org/maven2/ant-contrib/ant-contrib/1.0b3/ant-contrib-1.0b3.jar
        mv ant-contrib-1.0b3.jar /usr/share/ant/lib
        pip install acdh-tei-pyutils>=0.20.0
    - name: Fetch and preprocess Data
      run: |
        ./fetch_data.sh
