name: Setup Repository Dispatch Trigger

# This workflow needs to be added to the schnitzler-briefe-data repository
# It will trigger the PDF generation workflow when XML files are changed in schnitzler-briefe-tex

on:
  push:
    branches: [main]
    paths: ['data/editions/*.xml']

jobs:
  trigger-pdf-generation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Get changed XML files
      id: changes
      run: |
        CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD -- data/editions/*.xml)
        
        if [ -z "$CHANGED_FILES" ]; then
          echo "No XML files changed"
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "Changed XML files:"
          echo "$CHANGED_FILES"
          echo "has_changes=true" >> $GITHUB_OUTPUT
          
          # Create JSON payload with changed files
          FILES_JSON=$(echo "$CHANGED_FILES" | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "changed_files=$FILES_JSON" >> $GITHUB_OUTPUT
        fi

    - name: Trigger PDF generation workflow
      if: steps.changes.outputs.has_changes == 'true'
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: arthur-schnitzler/schnitzler-briefe-tex
        event-type: xml-files-changed
        client-payload: |
          {
            "changed_files": ${{ steps.changes.outputs.changed_files }},
            "commit_sha": "${{ github.sha }}",
            "commit_message": "${{ github.event.head_commit.message }}"
          }