name: 'Trigger actions in other repos on push'

on:
  push:
    branches:
      - main

jobs:
  # Existing job for schnitzler-briefe-tex
  dispatch_to_tex_repo:
    if: contains(join(github.event.commits.*.modified), 'data/editions/')
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        files: data/editions/*.xml
        files_separator: ','
    - name: Repository Dispatch to schnitzler-briefe-tex
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: arthur-schnitzler/schnitzler-briefe-tex
        event-type: xml-files-changed
        client-payload: |
          {
            "changed_files": "${{ steps.changed-files.outputs.all_changed_files }}",
            "sha": "${{ github.sha }}",
            "commit_message": "${{ github.event.head_commit.message }}"
          }

  # New job for schnitzler-briefe-charts
  dispatch_to_charts_repo:
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch to schnitzler-briefe-charts
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: arthur-schnitzler/schnitzler-briefe-charts
        event-type: data-updated
        client-payload: |
          {
            "sha": "${{ github.sha }}",
            "commit_message": "${{ github.event.head_commit.message }}"
          }

  # New job for schnitzler-tagebuch-charts when listcorrespondence.xml changes
  dispatch_to_tagebuch_charts:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Check if listcorrespondence.xml changed
      id: changed-listcorrespondence
      uses: tj-actions/changed-files@v45
      with:
        files: data/indices/listcorrespondence.xml
    - name: Repository Dispatch to schnitzler-tagebuch-charts
      if: steps.changed-listcorrespondence.outputs.any_changed == 'true'
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: arthur-schnitzler/schnitzler-tagebuch-charts
        event-type: update-korrespondenzpartner
        client-payload: |
          {
            "sha": "${{ github.sha }}",
            "commit_message": "${{ github.event.head_commit.message }}"
          }